apps/products/urls.py
from django.urls import path

from apps.products.views import product_list, product_detail, product_by_feature

app_name = 'products'
urlpatterns = [
    path('', product_list, name='product_list'),
    path('detail/<int:pk>/', product_detail, name='detail-page'),
    path('detail/feature/<int:pk>/', product_by_feature, name='product_by_feature'),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from apps.general.views import (
    set_language,
    home,
    checkout,
    search,
    set_currency,
    page_404,
    clear_session,
)

urlpatterns = [
    # =========== CKEDITOR URLS  ============
    path("__ckeditor5/", include('django_ckeditor_5.urls')),

    # =============MEDIA URLS===========
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),

    # =======SET LANGUAGE URLS =======
    path('set-language/<str:lang>/', set_language, name='set-lang'),

    # =======SET CURRENCY URLS =======
    path('set-currency/<str:currency>/', set_currency, name='set-currency'),
]
urlpatterns += i18n_patterns(
    path('', home, name='home-page'),
    path('admin/', admin.site.urls),

    # ======= General URLS =======

    path('checkout/', checkout, name='checkout-page'),
    path('search/', search, name='search'),
    path('clear-session/', clear_session, name='clear_session'),


    # ============= CATEGORIES URLS =============
    path('category/', include('apps.categories.urls', namespace='categories')),

    # ============= CONTACT URLS =============
    path('contact/', include('apps.contact.urls', namespace='contacts')),

    # ============= ABOUT URLS =============
    path('about/', include('apps.abouts.urls', namespace='about')),

    # ============= WISHLIST URLS =============
    path('wishlist/', include('apps.wishlist.urls', namespace='wishlists')),

    # ============= CART URLS =============
    path('cart/', include('apps.cart.urls', namespace='carts')),

    # ============= COUPONS URLS =============
    path('coupons', include('apps.coupons.urls', namespace='coupons')),

    # =============  PRODUCTS URLS =============
    path('products/', include('apps.products.urls', namespace='products')),

    # =============  COMMENTS URLS =============
    path('comments/', include('apps.comments.urls', namespace='comments')),

    # ============= AUTH URLS  =============
    path('auth/', include('apps.authentication.urls')),

    # ============= DEBUG_TOOLBAR URLs =============
    path('__debug__/', include('debug_toolbar.urls')),

    # ============= 404 URLS =============
    path('404/', page_404, name='404-page'),

)

apps/sellers/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _, get_language
from django.db import models

from apps.sellers.choices import SocialLinkType


class Seller(models.Model):
    class Gender(models.TextChoices):
        MALE = 'Male', _('Male')
        FEMALE = 'Female', _('Female')

    rating = models.IntegerField(verbose_name=_('rating'),
                                 validators=[MinValueValidator(0), MaxValueValidator(5)])
    seller_gender = models.CharField(verbose_name=_('Gender'), max_length=10, choices=Gender.choices)

    @property
    def detail(self):
        obj = SellerDetail.objects.get(seller_id=self.pk, language=get_language())
        return {
            'name': obj.name,
            'description': obj.description,
        }


class SellerDetail(models.Model):
    class Language(models.TextChoices):
        EN = 'en',
        RU = 'ru',
        UZ = 'uz'

    seller = models.ForeignKey(to=Seller, on_delete=models.CASCADE)
    name  = models.CharField(verbose_name=_('name'), max_length=50)
    description = models.TextField(verbose_name=_('description'), blank=True)
    language = models.CharField(verbose_name=_('language'), max_length=10, choices=Language.choices)


class SellerSocialLink(models.Model):
    social = models.PositiveSmallIntegerField(choices=SocialLinkType.choices)
    social_media = models.URLField(max_length=255, unique=True)

    def __str__(self):
        return self.social_media
# #!/usr/bin/env python
# """Django's command-line utility for administrative tasks."""
# import os
# import sys
#
#
# def main():
#     """Run administrative tasks."""
#     os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'contact.settings')
#     try:
#         from django.core.management import execute_from_command_line
#     except ImportError as exc:
#         raise ImportError(
#             "Couldn't import Django. Are you sure it's installed and "
#             "available on your PYTHONPATH environment variable? Did you "
#             "forget to activate a virtual environment?"
#         ) from exc
#     execute_from_command_line(sys.argv)
#
#
# if __name__ == '__main__':
#     main()

apps/sellers/views.py
from django.shortcuts import render

# Create your views here.

templates/includes/breadcrumb.html
<div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'home-page' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'products:product_list' %}">Shop</a>
                    <span class="breadcrumb-item active" style="color: blue">{{ page }}</span>
                </nav>
            </div>
        </div>
    </div>

templates/includes/sellers.html
{% load static %}
<!-- Guide start -->
        <div class="container-fluid guide py-5">
            <div class="container py-5">
                <div class="mx-auto text-center mb-5" style="max-width: 900px;">
                    <h5 class="section-title px-3">Travel Guide</h5>
                    <h1 class="mb-0">Meet Our Guide</h1>
                </div>
                <div class="row g-4">
                    <div class="col-md-6 col-lg-3">
                        <div class="guide-item">
                            <div class="guide-img">
                                <div class="guide-img-efects">
                                    <img src="{% static 'sellers/guide-1.jpg' %}" class="img-fluid w-100 rounded-top" alt="Image">
                                </div>
                                <div class="guide-icon rounded-pill p-2">
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-instagram"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="guide-title text-center rounded-bottom p-4">
                                <div class="guide-title-inner">
                                    <h4 class="mt-3">Full Name</h4>
                                    <p class="mb-0">Designation</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="guide-item">
                            <div class="guide-img">
                                <div class="guide-img-efects">
                                    <img src="{% static 'sellers/guide-2.jpg' %}" class="img-fluid w-100 rounded-top" alt="Image">
                                </div>
                                <div class="guide-icon rounded-pill p-2">
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-instagram"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="guide-title text-center rounded-bottom p-4">
                                <div class="guide-title-inner">
                                    <h4 class="mt-3">Full Name</h4>
                                    <p class="mb-0">Designation</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="guide-item">
                            <div class="guide-img">
                                <div class="guide-img-efects">
                                    <img src="{% static 'sellers/guide-3.jpg' %}" class="img-fluid w-100 rounded-top" alt="Image">
                                </div>
                                <div class="guide-icon rounded-pill p-2">
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-instagram"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="guide-title text-center rounded-bottom p-4">
                                <div class="guide-title-inner">
                                    <h4 class="mt-3">Full Name</h4>
                                    <p class="mb-0">Designation</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="guide-item">
                            <div class="guide-img">
                                <div class="guide-img-efects">
                                    <img src="{% static 'sellers/guide-4.jpg' %}" class="img-fluid w-100 rounded-top" alt="Image">
                                </div>
                                <div class="guide-icon rounded-pill p-2">
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-instagram"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="guide-title text-center rounded-bottom p-4">
                                <div class="guide-title-inner">
                                    <h4 class="mt-3">Full Name</h4>
                                    <p class="mb-0">Designation</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<!-- Guid end -->