apps/abouts/urls.py
from django.urls import path

from apps.abouts import views

app_name='about'

urlpatterns = [
    path('', views.about, name='about-page'),
]

apps/cart/urls.py
from django.urls import path
from apps.cart.views import cart
from apps.cart.views import create_cart, delete_cart,set_cart_quantity

app_name = 'carts'
urlpatterns = [
    path('', cart, name='cart-page'),
    path("create/<int:product_id>/", create_cart, name="create_cart"),
    path("delete/<int:product_id>/", delete_cart, name="delete_cart"),
    path("set/<int:user_cart_id>/", set_cart_quantity, name="set-cart-quantity"),
]

apps/contact/urls.py
from django.urls import path
from .views import create_contact,contact

app_name = 'contacts'
urlpatterns = [
    path('', contact, name='contact-page'),
    path('create/', create_contact, name='create_contact'),
]

apps/coupons/urls.py
from django.urls import path
from apps.coupons.views import check_coupon

app_name = 'coupons'
urlpatterns = [
    path('check/', check_coupon, name='check_coupon'),
]

apps/wishlist/urls.py
from django.urls import path
from .views import wishlist, wishlist_create, delete_wishlist

app_name = 'wishlists'
urlpatterns = [
    path("", wishlist, name="wishlist"),
    path("create/<int:product_id>/", wishlist_create, name="wishlist_create"),
    path("delete/<int:product_id>/", delete_wishlist, name="delete_wishlist"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from apps.general.views import (
    set_language,
    home,
    checkout,
    search,
    set_currency,
    page_404,
    clear_session,
)

urlpatterns = [
    # =========== CKEDITOR URLS  ============
    path("__ckeditor5/", include('django_ckeditor_5.urls')),

    # =============MEDIA URLS===========
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),

    # =======SET LANGUAGE URLS =======
    path('set-language/<str:lang>/', set_language, name='set-lang'),

    # =======SET CURRENCY URLS =======
    path('set-currency/<str:currency>/', set_currency, name='set-currency'),
]
urlpatterns += i18n_patterns(
    path('', home, name='home-page'),
    path('admin/', admin.site.urls),

    # ======= General URLS =======

    path('checkout/', checkout, name='checkout-page'),
    path('search/', search, name='search'),
    path('clear-session/', clear_session, name='clear_session'),


    # ============= CATEGORIES URLS =============
    path('category/', include('apps.categories.urls', namespace='categories')),

    # ============= CONTACT URLS =============
    path('contact/', include('apps.contact.urls', namespace='contacts')),

    # ============= ABOUT URLS =============
    path('about/', include('apps.abouts.urls', namespace='about')),

    # ============= WISHLIST URLS =============
    path('wishlist/', include('apps.wishlist.urls', namespace='wishlists')),

    # ============= CART URLS =============
    path('cart/', include('apps.cart.urls', namespace='carts')),

    # ============= COUPONS URLS =============
    path('coupons', include('apps.coupons.urls', namespace='coupons')),

    # =============  PRODUCTS URLS =============
    path('products/', include('apps.products.urls', namespace='products')),

    # =============  COMMENTS URLS =============
    path('comments/', include('apps.comments.urls', namespace='comments')),

    # ============= AUTH URLS  =============
    path('auth/', include('apps.authentication.urls')),

    # ============= DEBUG_TOOLBAR URLs =============
    path('__debug__/', include('debug_toolbar.urls')),

    # ============= 404 URLS =============
    path('404/', page_404, name='404-page'),

)

apps/abouts/models.py
from django.core.exceptions import ValidationError
from django.db import models


class About(models.Model):
    title = models.CharField(max_length=155)
    description = models.TextField(max_length=255, blank=True)
    image = models.ImageField(upload_to='abouts/images/%Y/%m/%d/')

    def __str__(self):
        return self.title

    def clean(self):
        if not self.pk and About.objects.exists():
            raise ValidationError("About object is already created !")

apps/cart/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from django.conf import settings


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)


    class Meta:
        unique_together = (('user', 'product'),)

apps/contact/models.py
from django.conf import settings
from django.db import models

class Contact(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,blank=True, null=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField(max_length=1000)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.user:
            self.name, self.email = self.user.first_name, self.user.email
        super().save(*args, **kwargs)

apps/wishlist/models.py
from django.conf import settings
from django.db import models


class Wishlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(to='products.product', on_delete=models.CASCADE)

    class Meta:
        unique_together = (('user', 'product'),)

apps/contact/forms.py
from apps.contact.models import Contact


from django import forms

class ContactCreateForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

apps/abouts/views.py
from django.shortcuts import render

from apps.abouts.models import About


def about(request):
    context = {
        'about': About.objects.first(),
        'page': 'about'
    }
    return render(request, 'about.html',context)

apps/cart/views.py
from decimal import Decimal

from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.db.models import F, Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from datetime import datetime

from apps.cart.models import Cart
from apps.coupons.models import UsedCoupon


@login_required(login_url=settings.LOGIN_URL)
def cart(request: WSGIRequest):
    user = request.user
    code = request.session.get('coupon_data', {}).get('code')
    coupon_data = request.session.get('coupon_data')

    if coupon_data:
        end_date = datetime.strptime(coupon_data['end_date'], '%Y-%m-%d').date()
    else:
        end_date = None

    now = datetime.date(datetime.now())

    if (code is not None
            and
            UsedCoupon.objects.filter(coupon__code=code, user_id=user.pk).exists()
            and now == end_date
    ):
        del request.session['coupon_data']

    queryset = Cart.objects.annotate(total_quantity=F('quantity') * F('product__price')).filter(
        user=request.user).select_related('product')

    context = {
        'user_carts': queryset,
        'cart_total_price': queryset.aggregate(Sum('total_quantity'))['total_quantity__sum']
    }

    return render(request=request, template_name='cart.html', context=context)


@login_required(login_url=settings.LOGIN_URL)
def create_cart(request: WSGIRequest, product_id: int):
    quantity = request.POST.get('cart_quantity', 1)
    obj, created = Cart.objects.get_or_create(user=request.user, product_id=product_id)
    if obj.quantity != quantity:
        obj.quantity = quantity
        obj.save()

    return redirect(request.META['HTTP_REFERER'])


def delete_cart(request: WSGIRequest, product_id: int) -> None:
    Cart.objects.filter(product_id=product_id).delete()
    return redirect(request.META['HTTP_REFERER'])


def set_cart_quantity(request, user_cart_id: int) -> None:
    if request.method == 'GET':
        return redirect('404-page')

    cart_obj = get_object_or_404(Cart, pk=user_cart_id)

    quantity = request.POST.get('user_cart_quantity', str(cart_obj.quantity))

    if quantity.isdigit() and int(quantity) <= 0:
        cart_obj.delete()
    else:
        cart_obj.quantity = quantity
        cart_obj.save()
    return redirect(request.META['HTTP_REFERER'])

apps/contact/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from apps.contact.forms import ContactCreateForm


def contact(request):
    return render(request=request, template_name='contact.html', context={'page': 'contact'})


def create_contact(request):
    if request.method == 'GET':
        return redirect('404-page')
    form = ContactCreateForm(data=request.POST)
    if form.is_valid():
        form.save()
        messages.success(request, 'Your message has been done!')
    else:
        messages.error(request, form.errors)


    return redirect(request.META.get('HTTP_REFERER'))

apps/wishlist/views.py
from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, redirect

from apps.wishlist.models import Wishlist


def wishlist(request: WSGIRequest):
    if not request.user.is_authenticated:
        return redirect('login-page')
    context = {
        'wishlists': Wishlist.objects.filter(user=request.user).select_related('product')
    }
    return render(request=request, template_name='wishlist.html', context=context)


@login_required(login_url='login-page')
def wishlist_create(request: WSGIRequest, product_id: int):
    Wishlist.objects.get_or_create(product_id=product_id, user=request.user)
    return redirect(request.META['HTTP_REFERER'])


def delete_wishlist(request: WSGIRequest, product_id: int) -> None:
    Wishlist.objects.filter(product_id=product_id).delete()
    return redirect(request.META['HTTP_REFERER'])

templates/about.html
{% extends 'bases/basic.html' %}
{% block content %}
{% load static %}
        <!-- About Start -->
        <div class="container-fluid about py-5">
            <div class="container py-5">
                <div class="row g-5 align-items-center">
                    <div class="col-lg-5">
                        <div class="h-100" style="border: 50px solid; border-color: transparent #13357B transparent #13357B;">
                            <img src="{{ about.image.url }}" class="img-fluid w-100 h-100" alt="">
                        </div>
                    </div>
                    <div class="col-lg-7" style="background: linear-gradient(rgba(255, 255, 255, .8), rgba(255, 255, 255, .8)), {% static 'about ing/about-img-1.png' %};">
                        <h5 class="section-about-title pe-3">About Us</h5>
                        <h1 class="mb-4">Welcome to <span class="text-primary">{{ about.title }}</span></h1>
                        <p class="mb-4">{{ about.description|safe  }}</p>

                        <div class="row gy-2 gx-4 mb-4">
{#                        {% for foo in social_media %}#}
                            <div class="col-sm-6">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>{{ foo.text }}</p>
                            </div>
{#                        {% endfor %}#}
                        </div>

                        <a class="btn btn-primary rounded-pill py-3 px-5 mt-2" href="">Read More</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- About End -->
{#    <!-- Sellers Start -->#}
{#    {% include 'includes/sellers.html' %}#}
{#    <!-- Sellers Start -->#}
    
{% endblock content %}

templates/cart.html
{% extends 'bases/basic.html' %}
{% load product_tags %}
{% load static %}
{% block content %}

    <!-- Breadcrumb Start -->
    {% include 'includes/breadcrumb.html' with page='Shopping cart' %}
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for user_cart in user_carts %}
                    	<tr>
                            <td class="align-middle"><img src="{{ user_cart.product.main_image.url }}" alt="" style="width: 50px;">{{ user_carts.product.title }}</td>
                            <td class="align-middle">$ {{ user_cart.product.price  }} </td>
                            <td class="align-middle">
                                <form action="{% url 'carts:set-cart-quantity' user_cart.pk %}" method="post">
                                    {% csrf_token %}
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-minus" >
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" name="user_cart_quantity"  value="{{ user_cart.quantity }}">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                                </form>    
                            </td>
                            <td class="align-middle">$ {{ user_cart.total_quantity }}</td>
                            <td class="align-middle">
                                <a href="{% url 'carts:delete_cart' user_cart.product.id %}">
                                    <button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                {% for message in messages %}
                	<p style="color: {% if message.level == 25 %} green {% elif message.level == 30 %} yellow {% else %} red {% endif %}">{{ message }}</p>
                {% endfor %}

                <form class="mb-30" action="{% url 'coupons:check_coupon' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4"  required
                               name="coupon_code" value="{{ request.session.coupon_data.code }}" placeholder="Coupon Code" >
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>$ {{ cart_total_price }} {{ request.session.currency }}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            {% str_to_decimal general.cart_shipping_percent as c_sh_p %}
                            {% multiply c_sh_p cart_total_price as ss %}
                            <h6 class="font-weight-medium">$ {{ ss }} {{ request.session.currency }}</h6>
                        </div>
                        <br>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Coupon</h6>
                            <h6 class="font-weight-medium">$ - {{request.session.coupon_data.discount_percent }} {{ request.session.currency }}</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                           
                            {% total_cal ss cart_total_price   as result %}
                            <h5>$ {{ result }} {{ request.session.currency }}</h5>
                        </div>
                        <a href="{% url 'checkout-page' %}"><button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Cart End -->

{% endblock content %}

templates/contact.html
{% extends 'bases/basic.html' %}
{% block content %}
    {% load static %}


    <!-- Breadcrumb Start -->
    {% include 'includes/breadcrumb.html' with page='Contact' %}
    <!-- Breadcrumb End -->


    <!-- Contact Start -->
    <div class="container-fluid">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Contact Us</span>
        </h2>
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5">
                <div class="contact-form bg-light p-30">
                    <div id="success"></div>
                    <form method="post" action="{% url 'contacts:create_contact' %}" name="sentMessage" id="contactForm"
                          novalidate="novalidate">
                    {% csrf_token %}
                        {% for message in messages %}
                            <p style="color: {% if message.level == 25 %} green {% endif %};">{{ message }}</p>
                        {% endfor %}

                        {% if not user.is_authenticated %}
                            <div class="control-group">
                                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name"
                                       required="required" data-validation-required-message="Please enter your name"/>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input type="email" name="email" class="form-control" id="email"
                                       placeholder="Your Email"
                                       required="required" data-validation-required-message="Please enter your email"/>
                                <p class="help-block text-danger"></p>
                            </div>
                            {% else %}
                                <input type="hidden" name="name" value="{{ user.get_full_name }}">
                                <input type="hidden" name="email" value="{{ user.email }}">
                        {% endif %}
                        <div class="control-group">
                            <input type="text" name="subject" class="form-control" id="subject" placeholder="Subject"
                                   required="required" data-validation-required-message="Please enter a subject"/>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <textarea class="form-control" name="message" rows="8" id="message" placeholder="Message"
                                      required="required"
                                      data-validation-required-message="Please enter your message"></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">Send
                                Message
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5 mb-5">
                <div class="bg-light p-30 mb-30">
                    <iframe style="width: 100%; height: 250px;"
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                            frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false"
                            tabindex="0"></iframe>
                </div>
                <div class="bg-light p-30 mb-3">
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->

    <script>
        $(function () {

            $("#contactForm input, #contactForm textarea").jqBootstrapValidation({
                preventSubmit: true,
                submitError: function ($form, event, errors) {
                },
                submitSuccess: function ($form, event) {
                    event.preventDefault();
                    var name = $("input#name").val();
                    var email = $("input#email").val();
                    var subject = $("input#subject").val();
                    var message = $("textarea#message").val();

                    $this = $("#sendMessageButton");
                    $this.prop("disabled", true);

                    $.ajax({
                        url: "contact.php",
                        type: "POST",
                        data: {
                            name: name,
                            email: email,
                            subject: subject,
                            message: message
                        },
                        cache: false,
                        success: function () {
                            $('#success').html("<div class='alert alert-success'>");
                            $('#success > .alert-success').html("<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;")
                                .append("</button>");
                            $('#success > .alert-success')
                                .append("<strong>Your message has been sent. </strong>");
                            $('#success > .alert-success')
                                .append('</div>');
                            $('#contactForm').trigger("reset");
                        },
                        error: function () {
                            $('#success').html("<div class='alert alert-danger'>");
                            $('#success > .alert-danger').html("<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;")
                                .append("</button>");
                            $('#success > .alert-danger').append($("<strong>").text("hello " + name + ", it seems that our mail server is not responding. Please try again later!"));
                            $('#success > .alert-danger').append('</div>');
                            $('#contactForm').trigger("reset");
                        },
                        complete: function () {
                            setTimeout(function () {
                                $this.prop("disabled", false);
                            }, 1000);
                        }
                    });
                },
                filter: function () {
                    return $(this).is(":visible");
                },
            });

            $("a[data-toggle=\"tab\"]").click(function (e) {
                e.preventDefault();
                $(this).tab("show");
            });
        });

        $('#name').focus(function () {
            $('#success').html('');
        });

    </script>

{% endblock content %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% for seller_detail in seller_details %}
    <p>=======================================</p>
	<p><b>rating: </b>{{ seller_detail.seller.rating}}</p>
	<p><b>name: </b>{{ seller_detail.name }}</p>
	<p><b>description: </b>{{ seller_detail.description }}</p>
	<p><b>language: </b>{{ seller_detail.language }}</p>
{% endfor %}

</body>
</html>

templates/wishlist.html
{% extends 'bases/basic.html' %}
{% load static %}
{% block content %}

    <!-- Breadcrumb Start -->
    {% include 'includes/breadcrumb.html' with page='Shopping cart' %}
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Images</th>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for wishlist in wishlists %}
                    	<tr>
                            <td class="align-middle"><img src="{{ wishlist.product.main_image.url }}" alt="" style="width: 100px; height: auto;"></td>
                            <td style="width: 500px" class="align-middle">{{ wishlist.product.title }}</td>
                            <td class="align-middle">{{ wishlist.product.price }}</td>
                            <td class="align-middle">
                                <a class="btn btn-sm btn-danger" href="{% url 'wishlists:delete_wishlist' product_id=wishlist.product.id %}" >
                                    <i class="fa fa-times"></i>   
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock content %}